### ISSUE TITLE
all_revenues

### ISSUE THREAD

**Issue by Kungie** [furkankilicc/twitch-csv-read#1]
Dostum all_revenues dosyasına nerden ulaşabiliriz onu yazmamışsın ya da ben göremedim

**Comment by BarisX** [comment]
you cant find it here

**Comment by Kungie** [comment]
How can I find it? Can you send me the file via weshare or sth if you have?

**Comment by Kungie** [comment]
> you cant find it here

How can I find it? Can you send me the file via weshare or sth if you have?

**Comment by BarisX** [comment]
no one can take its responsibilities

**Comment by Kungie** [comment]
> no one can take its responsibilities

Alright, I'll try to find it on my own.
